---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Purchase
  labels:
    app: Purchase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Purchase
  template:
    metadata:
      labels:
        app: Purchase
    spec:
      containers:
        - name: Purchase
          image: username/Purchase:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Billing
  labels:
    app: Billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Billing
  template:
    metadata:
      labels:
        app: Billing
    spec:
      containers:
        - name: Billing
          image: username/Billing:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Consign
  labels:
    app: Consign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Consign
  template:
    metadata:
      labels:
        app: Consign
    spec:
      containers:
        - name: Consign
          image: username/Consign:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Stock
  labels:
    app: Stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Stock
  template:
    metadata:
      labels:
        app: Stock
    spec:
      containers:
        - name: Stock
          image: username/Stock:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DashBoard
  labels:
    app: DashBoard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DashBoard
  template:
    metadata:
      labels:
        app: DashBoard
    spec:
      containers:
        - name: DashBoard
          image: username/DashBoard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Purchase
  labels:
    app: Purchase
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Purchase


---


apiVersion: v1
kind: Service
metadata:
  name: Billing
  labels:
    app: Billing
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Billing


---


apiVersion: v1
kind: Service
metadata:
  name: Consign
  labels:
    app: Consign
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Consign


---


apiVersion: v1
kind: Service
metadata:
  name: Stock
  labels:
    app: Stock
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Stock


---


apiVersion: v1
kind: Service
metadata:
  name: DashBoard
  labels:
    app: DashBoard
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DashBoard

